POST http://localhost:7071/api/http_trigger
Content-Type: application/json
x-functions-key: {{FUNC_KEY}}

{
  "timestamp": "2025-12-16T15:42:30.123Z",
  "sensor": {
    "ax": 0.05,
    "ay": -0.12,
    "az": 9.78,
    "gx": 0.02,
    "gy": 0.01,
    "gz": -0.03
  },
  "isFall": false
}
